"""
video_call/serializers.py

DRF serializers for Room model validation and serialization.

Serializers:
    RoomSerializer       — Full read serializer for Room responses.
    CreateRoomSerializer — Validates name input for room creation.
    JoinRoomSerializer   — Validates room_code + user_name for room joining.
"""

from rest_framework import serializers

from .models import Room


class RoomSerializer(serializers.ModelSerializer):
    """
    Full serializer for the Room model.

    Used in RoomDetailView and any response that needs complete room data.

    Fields:
        id, room_code, name, created_at,
        is_active, max_participants, current_participants
    """

    class Meta:
        model = Room
        fields = [
            "id",
            "room_code",
            "name",
            "created_at",
            "is_active",
            "max_participants",
            "current_participants",
        ]
        read_only_fields = ["id", "room_code", "created_at"]


class CreateRoomSerializer(serializers.Serializer):
    """
    Validates the request body for POST /api/rooms/create/.

    Only accepts a room name — room_code is auto-generated by Room.save().

    Fields:
        name (str): Room display name, 2–50 characters.
    """

    name = serializers.CharField(
        max_length=50,
        help_text="Room display name (2–50 characters).",
    )

    def validate_name(self, value: str) -> str:
        """
        Strip surrounding whitespace and enforce length constraints.

        Args:
            value: Raw name string from request body.

        Returns:
            str: Cleaned name string.

        Raises:
            ValidationError: If name is shorter than 2 chars after stripping.
        """
        value = value.strip()
        if len(value) < 2:
            raise serializers.ValidationError(
                "Room name must be at least 2 characters long."
            )
        return value


class JoinRoomSerializer(serializers.Serializer):
    """
    Validates the request body for POST /api/rooms/join/.

    Checks that the room exists, is active, and has available capacity.

    Fields:
        room_code (str): 8-character room code.
        user_name (str): Display name of the joining user (2–50 chars).
    """

    room_code = serializers.CharField(
        max_length=8,
        min_length=8,
        help_text="8-character alphanumeric room code.",
    )
    user_name = serializers.CharField(
        max_length=50,
        help_text="Display name of the user joining the room.",
    )

    def validate_room_code(self, value: str) -> str:
        """
        Normalize to uppercase, check room exists, is active, and not full.

        Args:
            value: Raw room_code string from request body.

        Returns:
            str: Uppercased room_code if valid.

        Raises:
            ValidationError: If room does not exist, is inactive, or is full.
        """
        value = value.upper().strip()

        try:
            room = Room.objects.get(room_code=value)
        except Room.DoesNotExist:
            raise serializers.ValidationError("Room not found.")

        if not room.is_active:
            raise serializers.ValidationError("This room is no longer active.")

        if room.is_full():
            raise serializers.ValidationError(
                f"Room is full (max {room.max_participants} participants)."
            )

        return value

    def validate_user_name(self, value: str) -> str:
        """
        Strip whitespace and enforce min length for user display name.

        Args:
            value: Raw user_name string from request body.

        Returns:
            str: Cleaned user_name string.

        Raises:
            ValidationError: If name is shorter than 2 chars after stripping.
        """
        value = value.strip()
        if len(value) < 2:
            raise serializers.ValidationError(
                "User name must be at least 2 characters long."
            )
        return value
